---

# Look in `.env` for configuration.

services:
  myspace-pubsub:
    image: ${IMAGE}
    env_file: .env
  vault:
    image: ${VAULT_IMAGE}
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:${VAULT_PORT}:${VAULT_PORT}"
      - ":::${VAULT_PORT}:${VAULT_PORT}"
    env_file: .env
