---

# Look in `.env` for configuration.

services:
  go-space:
    image: ${IMAGE}
    hostname: go-space
    env_file: .env
#    ports:
#      - "127.0.0.1:${SPACE_NODE_PORT}:${SPACE_NODE_PORT}"
#      - ":::${SPACE_NODE_PORT}:${SPACE_NODE_PORT}"
  vault:
    image: ${VAULT_IMAGE}
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:${VAULT_PORT}:${VAULT_PORT}"
      - ":::${VAULT_PORT}:${VAULT_PORT}"
    env_file: .env
#  space:
#    image: ${SPACE_ELIXIR_IMAGE}
#    hostname: space
#    env_file: .env
#    stdin_open: true 
#    tty: true
#    command:
#      - iex
#      - --sname
#      - ${SPACE_SPACE_NODE_NAME}
#      - --cookie
#      - ${SPACE_NODE_COOKIE}
